BANCOS = [
    "Tenpo Prepago S.a.",
    "Banco Del Estado De Chile",
    "Banco Ripley",
    "Banco Bice",
    "Banco Consorcio",
    "Banco Credito Inversiones",
    "Banco De Chile",
    "Banco Falabella",
    "Banco Internacional",
    "Banco Itau Corpbanca",
    "Banco Santander-santiago",
    "Banco Security",
    "Coopeuch",
    "Copec Pay",
    "Mercado Pago Emisora S.a.",
    "Scotiabank Sud Americano",
    "Tapp Caja Los Andes",
]