
ELEMENTOS_MAP = {
  "PLAN DUO CLASICO": 1,          
  "PLAN DUO PREMIUM": 2,
  "PLAN DUO SUPERIOR": 3,
  "INTERNET CLASICO": 7,
  "INTERNET PREMIUM": 8,
  "INTERNET SUPERIOR": 9,
  "TV FIBRA OPTICA": 10,
  "TV ANALOGO": 12,
  "ANEXO": 14,
  "PLAN DUO CLASICO + ANEXOS": 15,
  "PLAN DUO PREMIUM + ANEXOS": 16,
  "PLAN DUO SUPERIOR + ANEXOS": 17,
  "TV FIBRA OPTICA + ANEXOS": 18,
  "TV ANALOGO + ANEXOS": 19,
  "SERVICIO TV": 20,
  "SERVICIO TV E INTERNET": 21,
  "SERVICIO INTERNET": 22,
  "DONACION": 23,
  "SINTONIZADOR": 24,
  "MIGRACION TV DIGITAL": 25,
  "MIGRACION TV DIGITAL + ANEXO": 26,
  "EXTENSOR DE WIFI": 27,
  "ANEXO EXTERIOR": 28,
  "TV ANALOGO QUELLON": 29        
}

ELEMENTOS = list(ELEMENTOS_MAP.keys())