ELEMENTOS= [
    "Plan Duo Clasico",
    "Plan Duo Premium",
    "Plan Duo Superior",
    "Plan Duo Clasico + Anexo",
    "Plan Duo Premium + Anexo",
    "Plan Duo Superior + Anexo",
    "Internet Clasico",
    "Internet Premium",
    "Internet Superior",
    "Servicio TV Fibra Optica",
    "Servicio TV Fibra Optica + Anexo",
    "Cambio Domicilio",
    "Instalacion Extensor WIFI",
    "Servicio TV Analogo",
    "Servicio TV Analogo + Anexo",
    "Servicios Extras",
    "Plan Empresa",
]