TECNICOS= [
    "Cristian Quiroz",
    "Miguel Mellado",
    "Juan Carlos Castillo",
    "Isidoro Molina",
    "Lucas Vega",
    "Rodrigo Castillo",
    "Sergio Sepulveda",
    "Felipe Astroza",
    "Paulina Pino",
    "Richard Poveda",
    "Francisco Parra",
    "Victor Saez",
    "Victor Rivera",
    "Yeihson Cuevas",
    "Javier Arriaza",
    "Sergio Potter",
    "Ricardo Gomez",
    "Manuel Espinoza",
    "Brian Escobar",
    "Daniela Salcedo",
    "Luis Veloso",
    "Christhofer Villablanca",
    "Jhon Vega",
    "Leonel Veliz",
    "Eduardo Burnes",
]